# .github/workflows/arc-test.yml
name: ARC Scaling Test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  test-scaling:
    # 关键：指定你在 values.yaml 中配置的 runnerScaleSetName
    runs-on: k8s-runner-group-ppu1
    container:
      image: reg.docker.alibaba-inc.com/ai-tmp/llm:pytorch2.9.0-ubuntu24.04-cuda13.0-sglang0.5.10-py312-ppu202605281910
    steps:
      - name: Hello World
        run: |
          echo "我跑在 K8s 自动拉起的 Pod 里！"
          hostname
          ppu-smi
